services:
  - type: web
    name: openwallets
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      bash -c "
      python OpenWallets/manage.py migrate &&
      python OpenWallets/manage.py collectstatic --noinput &&
      gunicorn --chdir OpenWallets OpenWallets.wsgi:application
      "
